export const propertiesToSelect = [
  'Market and Exchange Names',
  'As of Date in Form YYYY-MM-DD',
  'Open Interest (All)',
  'Noncommercial Positions-Long (All)',
  'Noncommercial Positions-Short (All)',
  'Commercial Positions-Long (All)',
  'Commercial Positions-Short (All)',
  'Change in Noncommercial-Long (All)',
  'Change in Noncommercial-Short (All)',
  'Change in Commercial-Long (All)',
  'Change in Commercial-Short (All)',
  '% of OI-Noncommercial-Long (All)',
  '% of OI-Noncommercial-Short (All)',
  '% of OI-Commercial-Long (All)',
  '% of OI-Commercial-Short (All)',

  'Noncommercial Positions-Spreading (All)',
  'Total Reportable Positions-Long (All)',
  'Total Reportable Positions-Short (All)',

  'Concentration-Gross LT =4 TDR-Long (All)',
  'Concentration-Gross LT =4 TDR-Short (All)',
  'Concentration-Gross LT =8 TDR-Long (All)',
  'Concentration-Gross LT =8 TDR-Short (All)',
  'Concentration-Net LT =4 TDR-Long (All)',
  'Concentration-Net LT =4 TDR-Short (All)',
  'Concentration-Net LT =8 TDR-Long (All)',
  'Concentration-Net LT =8 TDR-Short (All)',
  'Concentration-Gross LT = 4 TDR-Long (All)',
  'Concentration-Gross LT =4 TDR-Short (All)',
  'Concentration-Gross LT =8 TDR-Long (All)',
  'Concentration-Gross LT =8 TDR-Short (All)',
  'Concentration-Net LT =4 TDR-Long (All)',
  'Concentration-Net LT =4 TDR-Short (All)',
  'Concentration-Net LT =8 TDR-Long (All)',
  'Concentration-Net LT =8 TDR-Short (All)',

  'Traders-Total (All)',
  'Traders-Noncommercial-Long (All)',
  'Traders-Noncommercial-Short (All)',
  'Traders-Noncommercial-Spreading (All)',
  'Traders-Commercial-Long (All)',
  'Traders-Commercial-Short (All)',
] as const
