import { COTData } from './types'

export const testData: COTData = {
  'ICE FUTURES U.S.': {
    'U.S. DOLLAR INDEX': [
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-07-07',
        'Open Interest (All)': '22898',
        'Noncommercial Positions-Long (All)': '12150',
        'Noncommercial Positions-Short (All)': '17075',
        'Commercial Positions-Long (All)': '6316',
        'Commercial Positions-Short (All)': '857',
        'Change in Noncommercial-Long (All)': '2327',
        'Change in Noncommercial-Short (All)': '2288',
        'Change in Commercial-Long (All)': '378',
        'Change in Commercial-Short (All)': '-84',
        '% of OI-Noncommercial-Long (All)': '53.1',
        '% of OI-Noncommercial-Short (All)': '74.6',
        '% of OI-Commercial-Long (All)': '27.6',
        '% of OI-Commercial-Short (All)': '3.7',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-06-30',
        'Open Interest (All)': '19470',
        'Noncommercial Positions-Long (All)': '9823',
        'Noncommercial Positions-Short (All)': '14787',
        'Commercial Positions-Long (All)': '5938',
        'Commercial Positions-Short (All)': '940',
        'Change in Noncommercial-Long (All)': '-1838',
        'Change in Noncommercial-Short (All)': '-2180',
        'Change in Commercial-Long (All)': '-724',
        'Change in Commercial-Short (All)': '83',
        '% of OI-Noncommercial-Long (All)': '50.5',
        '% of OI-Noncommercial-Short (All)': '75.9',
        '% of OI-Commercial-Long (All)': '30.5',
        '% of OI-Commercial-Short (All)': '4.8',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-06-23',
        'Open Interest (All)': '21629',
        'Noncommercial Positions-Long (All)': '11661',
        'Noncommercial Positions-Short (All)': '16967',
        'Commercial Positions-Long (All)': '6662',
        'Commercial Positions-Short (All)': '857',
        'Change in Noncommercial-Long (All)': '860',
        'Change in Noncommercial-Short (All)': '827',
        'Change in Commercial-Long (All)': '1037',
        'Change in Commercial-Short (All)': '374',
        '% of OI-Noncommercial-Long (All)': '53.9',
        '% of OI-Noncommercial-Short (All)': '78.4',
        '% of OI-Commercial-Long (All)': '30.8',
        '% of OI-Commercial-Short (All)': '4.0',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-06-16',
        'Open Interest (All)': '19897',
        'Noncommercial Positions-Long (All)': '10802',
        'Noncommercial Positions-Short (All)': '16140',
        'Commercial Positions-Long (All)': '5625',
        'Commercial Positions-Short (All)': '483',
        'Change in Noncommercial-Long (All)': '-10084',
        'Change in Noncommercial-Short (All)': '-47',
        'Change in Commercial-Long (All)': '-1697',
        'Change in Commercial-Short (All)': '-12167',
        '% of OI-Noncommercial-Long (All)': '54.3',
        '% of OI-Noncommercial-Short (All)': '81.1',
        '% of OI-Commercial-Long (All)': '28.3',
        '% of OI-Commercial-Short (All)': '2.4',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-06-09',
        'Open Interest (All)': '33959',
        'Noncommercial Positions-Long (All)': '20886',
        'Noncommercial Positions-Short (All)': '16187',
        'Commercial Positions-Long (All)': '7322',
        'Commercial Positions-Short (All)': '12650',
        'Change in Noncommercial-Long (All)': '3003',
        'Change in Noncommercial-Short (All)': '6566',
        'Change in Commercial-Long (All)': '3666',
        'Change in Commercial-Short (All)': '134',
        '% of OI-Noncommercial-Long (All)': '61.5',
        '% of OI-Noncommercial-Short (All)': '47.7',
        '% of OI-Commercial-Long (All)': '21.6',
        '% of OI-Commercial-Short (All)': '37.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-06-02',
        'Open Interest (All)': '26044',
        'Noncommercial Positions-Long (All)': '17883',
        'Noncommercial Positions-Short (All)': '9621',
        'Commercial Positions-Long (All)': '3656',
        'Commercial Positions-Short (All)': '12516',
        'Change in Noncommercial-Long (All)': '-3164',
        'Change in Noncommercial-Short (All)': '3379',
        'Change in Commercial-Long (All)': '889',
        'Change in Commercial-Short (All)': '-6690',
        '% of OI-Noncommercial-Long (All)': '68.7',
        '% of OI-Noncommercial-Short (All)': '36.9',
        '% of OI-Commercial-Long (All)': '14.0',
        '% of OI-Commercial-Short (All)': '48.1',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-05-26',
        'Open Interest (All)': '28329',
        'Noncommercial Positions-Long (All)': '21046',
        'Noncommercial Positions-Short (All)': '6241',
        'Commercial Positions-Long (All)': '2767',
        'Commercial Positions-Short (All)': '19206',
        'Change in Noncommercial-Long (All)': '-3478',
        'Change in Noncommercial-Short (All)': '-979',
        'Change in Commercial-Long (All)': '-90',
        'Change in Commercial-Short (All)': '-2061',
        '% of OI-Noncommercial-Long (All)': '74.3',
        '% of OI-Noncommercial-Short (All)': '22.0',
        '% of OI-Commercial-Long (All)': '9.8',
        '% of OI-Commercial-Short (All)': '67.8',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-05-19',
        'Open Interest (All)': '31509',
        'Noncommercial Positions-Long (All)': '24525',
        'Noncommercial Positions-Short (All)': '7220',
        'Commercial Positions-Long (All)': '2857',
        'Commercial Positions-Short (All)': '21267',
        'Change in Noncommercial-Long (All)': '559',
        'Change in Noncommercial-Short (All)': '-288',
        'Change in Commercial-Long (All)': '214',
        'Change in Commercial-Short (All)': '228',
        '% of OI-Noncommercial-Long (All)': '77.8',
        '% of OI-Noncommercial-Short (All)': '22.9',
        '% of OI-Commercial-Long (All)': '9.1',
        '% of OI-Commercial-Short (All)': '67.5',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-05-12',
        'Open Interest (All)': '31156',
        'Noncommercial Positions-Long (All)': '23966',
        'Noncommercial Positions-Short (All)': '7508',
        'Commercial Positions-Long (All)': '2643',
        'Commercial Positions-Short (All)': '21040',
        'Change in Noncommercial-Long (All)': '-760',
        'Change in Noncommercial-Short (All)': '-784',
        'Change in Commercial-Long (All)': '253',
        'Change in Commercial-Short (All)': '132',
        '% of OI-Noncommercial-Long (All)': '76.9',
        '% of OI-Noncommercial-Short (All)': '24.1',
        '% of OI-Commercial-Long (All)': '8.5',
        '% of OI-Commercial-Short (All)': '67.5',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-05-05',
        'Open Interest (All)': '31600',
        'Noncommercial Positions-Long (All)': '24726',
        'Noncommercial Positions-Short (All)': '8292',
        'Commercial Positions-Long (All)': '2391',
        'Commercial Positions-Short (All)': '20908',
        'Change in Noncommercial-Long (All)': '-1557',
        'Change in Noncommercial-Short (All)': '-1894',
        'Change in Commercial-Long (All)': '-180',
        'Change in Commercial-Short (All)': '986',
        '% of OI-Noncommercial-Long (All)': '78.2',
        '% of OI-Noncommercial-Short (All)': '26.2',
        '% of OI-Commercial-Long (All)': '7.6',
        '% of OI-Commercial-Short (All)': '66.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-04-28',
        'Open Interest (All)': '32665',
        'Noncommercial Positions-Long (All)': '26283',
        'Noncommercial Positions-Short (All)': '10186',
        'Commercial Positions-Long (All)': '2570',
        'Commercial Positions-Short (All)': '19922',
        'Change in Noncommercial-Long (All)': '1423',
        'Change in Noncommercial-Short (All)': '951',
        'Change in Commercial-Long (All)': '230',
        'Change in Commercial-Short (All)': '37',
        '% of OI-Noncommercial-Long (All)': '80.5',
        '% of OI-Noncommercial-Short (All)': '31.2',
        '% of OI-Commercial-Long (All)': '7.9',
        '% of OI-Commercial-Short (All)': '61.0',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-04-21',
        'Open Interest (All)': '31439',
        'Noncommercial Positions-Long (All)': '24860',
        'Noncommercial Positions-Short (All)': '9235',
        'Commercial Positions-Long (All)': '2341',
        'Commercial Positions-Short (All)': '19885',
        'Change in Noncommercial-Long (All)': '992',
        'Change in Noncommercial-Short (All)': '730',
        'Change in Commercial-Long (All)': '-12',
        'Change in Commercial-Short (All)': '1421',
        '% of OI-Noncommercial-Long (All)': '79.1',
        '% of OI-Noncommercial-Short (All)': '29.4',
        '% of OI-Commercial-Long (All)': '7.4',
        '% of OI-Commercial-Short (All)': '63.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-04-14',
        'Open Interest (All)': '29702',
        'Noncommercial Positions-Long (All)': '23868',
        'Noncommercial Positions-Short (All)': '8505',
        'Commercial Positions-Long (All)': '2353',
        'Commercial Positions-Short (All)': '18464',
        'Change in Noncommercial-Long (All)': '1044',
        'Change in Noncommercial-Short (All)': '709',
        'Change in Commercial-Long (All)': '286',
        'Change in Commercial-Short (All)': '163',
        '% of OI-Noncommercial-Long (All)': '80.4',
        '% of OI-Noncommercial-Short (All)': '28.6',
        '% of OI-Commercial-Long (All)': '7.9',
        '% of OI-Commercial-Short (All)': '62.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-04-07',
        'Open Interest (All)': '28737',
        'Noncommercial Positions-Long (All)': '22823',
        'Noncommercial Positions-Short (All)': '7796',
        'Commercial Positions-Long (All)': '2067',
        'Commercial Positions-Short (All)': '18301',
        'Change in Noncommercial-Long (All)': '-130',
        'Change in Noncommercial-Short (All)': '-1092',
        'Change in Commercial-Long (All)': '-16',
        'Change in Commercial-Short (All)': '541',
        '% of OI-Noncommercial-Long (All)': '79.4',
        '% of OI-Noncommercial-Short (All)': '27.1',
        '% of OI-Commercial-Long (All)': '7.2',
        '% of OI-Commercial-Short (All)': '63.7',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-03-31',
        'Open Interest (All)': '29015',
        'Noncommercial Positions-Long (All)': '22953',
        'Noncommercial Positions-Short (All)': '8888',
        'Commercial Positions-Long (All)': '2083',
        'Commercial Positions-Short (All)': '17760',
        'Change in Noncommercial-Long (All)': '497',
        'Change in Noncommercial-Short (All)': '-1054',
        'Change in Commercial-Long (All)': '29',
        'Change in Commercial-Short (All)': '2127',
        '% of OI-Noncommercial-Long (All)': '79.1',
        '% of OI-Noncommercial-Short (All)': '30.6',
        '% of OI-Commercial-Long (All)': '7.2',
        '% of OI-Commercial-Short (All)': '61.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-03-24',
        'Open Interest (All)': '28353',
        'Noncommercial Positions-Long (All)': '22456',
        'Noncommercial Positions-Short (All)': '9942',
        'Commercial Positions-Long (All)': '2054',
        'Commercial Positions-Short (All)': '15633',
        'Change in Noncommercial-Long (All)': '2917',
        'Change in Noncommercial-Short (All)': '-2456',
        'Change in Commercial-Long (All)': '183',
        'Change in Commercial-Short (All)': '4743',
        '% of OI-Noncommercial-Long (All)': '79.2',
        '% of OI-Noncommercial-Short (All)': '35.1',
        '% of OI-Commercial-Long (All)': '7.2',
        '% of OI-Commercial-Short (All)': '55.1',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-03-17',
        'Open Interest (All)': '25344',
        'Noncommercial Positions-Long (All)': '19539',
        'Noncommercial Positions-Short (All)': '12398',
        'Commercial Positions-Long (All)': '1871',
        'Commercial Positions-Short (All)': '10890',
        'Change in Noncommercial-Long (All)': '-6063',
        'Change in Noncommercial-Short (All)': '-792',
        'Change in Commercial-Long (All)': '-8680',
        'Change in Commercial-Short (All)': '-14538',
        '% of OI-Noncommercial-Long (All)': '77.1',
        '% of OI-Noncommercial-Short (All)': '48.9',
        '% of OI-Commercial-Long (All)': '7.4',
        '% of OI-Commercial-Short (All)': '43.0',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-03-10',
        'Open Interest (All)': '44967',
        'Noncommercial Positions-Long (All)': '25602',
        'Noncommercial Positions-Short (All)': '13190',
        'Commercial Positions-Long (All)': '10551',
        'Commercial Positions-Short (All)': '25428',
        'Change in Noncommercial-Long (All)': '-6266',
        'Change in Noncommercial-Short (All)': '3769',
        'Change in Commercial-Long (All)': '6872',
        'Change in Commercial-Short (All)': '-2125',
        '% of OI-Noncommercial-Long (All)': '56.9',
        '% of OI-Noncommercial-Short (All)': '29.3',
        '% of OI-Commercial-Long (All)': '23.5',
        '% of OI-Commercial-Short (All)': '56.5',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-03-03',
        'Open Interest (All)': '39834',
        'Noncommercial Positions-Long (All)': '31868',
        'Noncommercial Positions-Short (All)': '9421',
        'Commercial Positions-Long (All)': '3680',
        'Commercial Positions-Short (All)': '27553',
        'Change in Noncommercial-Long (All)': '-7894',
        'Change in Noncommercial-Short (All)': '-5266',
        'Change in Commercial-Long (All)': '514',
        'Change in Commercial-Short (All)': '-2418',
        '% of OI-Noncommercial-Long (All)': '80.0',
        '% of OI-Noncommercial-Short (All)': '23.7',
        '% of OI-Commercial-Long (All)': '9.2',
        '% of OI-Commercial-Short (All)': '69.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-02-25',
        'Open Interest (All)': '47901',
        'Noncommercial Positions-Long (All)': '39762',
        'Noncommercial Positions-Short (All)': '14688',
        'Commercial Positions-Long (All)': '3165',
        'Commercial Positions-Short (All)': '29970',
        'Change in Noncommercial-Long (All)': '-638',
        'Change in Noncommercial-Short (All)': '-1484',
        'Change in Commercial-Long (All)': '-4',
        'Change in Commercial-Short (All)': '1050',
        '% of OI-Noncommercial-Long (All)': '83.0',
        '% of OI-Noncommercial-Short (All)': '30.7',
        '% of OI-Commercial-Long (All)': '6.6',
        '% of OI-Commercial-Short (All)': '62.6',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-02-18',
        'Open Interest (All)': '48475',
        'Noncommercial Positions-Long (All)': '40400',
        'Noncommercial Positions-Short (All)': '16172',
        'Commercial Positions-Long (All)': '3169',
        'Commercial Positions-Short (All)': '28920',
        'Change in Noncommercial-Long (All)': '-1314',
        'Change in Noncommercial-Short (All)': '-6063',
        'Change in Commercial-Long (All)': '-93',
        'Change in Commercial-Short (All)': '4688',
        '% of OI-Noncommercial-Long (All)': '83.3',
        '% of OI-Noncommercial-Short (All)': '33.4',
        '% of OI-Commercial-Long (All)': '6.5',
        '% of OI-Commercial-Short (All)': '59.7',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-02-11',
        'Open Interest (All)': '49644',
        'Noncommercial Positions-Long (All)': '41714',
        'Noncommercial Positions-Short (All)': '22235',
        'Commercial Positions-Long (All)': '3262',
        'Commercial Positions-Short (All)': '24232',
        'Change in Noncommercial-Long (All)': '11750',
        'Change in Noncommercial-Short (All)': '9406',
        'Change in Commercial-Long (All)': '644',
        'Change in Commercial-Short (All)': '3144',
        '% of OI-Noncommercial-Long (All)': '84.0',
        '% of OI-Noncommercial-Short (All)': '44.8',
        '% of OI-Commercial-Long (All)': '6.6',
        '% of OI-Commercial-Short (All)': '48.8',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-02-04',
        'Open Interest (All)': '36883',
        'Noncommercial Positions-Long (All)': '29964',
        'Noncommercial Positions-Short (All)': '12829',
        'Commercial Positions-Long (All)': '2618',
        'Commercial Positions-Short (All)': '21088',
        'Change in Noncommercial-Long (All)': '1648',
        'Change in Noncommercial-Short (All)': '948',
        'Change in Commercial-Long (All)': '602',
        'Change in Commercial-Short (All)': '1026',
        '% of OI-Noncommercial-Long (All)': '81.2',
        '% of OI-Noncommercial-Short (All)': '34.8',
        '% of OI-Commercial-Long (All)': '7.1',
        '% of OI-Commercial-Short (All)': '57.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-01-28',
        'Open Interest (All)': '36008',
        'Noncommercial Positions-Long (All)': '28316',
        'Noncommercial Positions-Short (All)': '11881',
        'Commercial Positions-Long (All)': '2016',
        'Commercial Positions-Short (All)': '20062',
        'Change in Noncommercial-Long (All)': '2982',
        'Change in Noncommercial-Short (All)': '-513',
        'Change in Commercial-Long (All)': '-2563',
        'Change in Commercial-Short (All)': '1490',
        '% of OI-Noncommercial-Long (All)': '78.6',
        '% of OI-Noncommercial-Short (All)': '33.0',
        '% of OI-Commercial-Long (All)': '5.6',
        '% of OI-Commercial-Short (All)': '55.7',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-01-21',
        'Open Interest (All)': '35887',
        'Noncommercial Positions-Long (All)': '25334',
        'Noncommercial Positions-Short (All)': '12394',
        'Commercial Positions-Long (All)': '4578',
        'Commercial Positions-Short (All)': '18572',
        'Change in Noncommercial-Long (All)': '-256',
        'Change in Noncommercial-Short (All)': '67',
        'Change in Commercial-Long (All)': '-260',
        'Change in Commercial-Short (All)': '57',
        '% of OI-Noncommercial-Long (All)': '70.6',
        '% of OI-Noncommercial-Short (All)': '34.5',
        '% of OI-Commercial-Long (All)': '12.8',
        '% of OI-Commercial-Short (All)': '51.8',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-01-14',
        'Open Interest (All)': '36196',
        'Noncommercial Positions-Long (All)': '25590',
        'Noncommercial Positions-Short (All)': '12327',
        'Commercial Positions-Long (All)': '4838',
        'Commercial Positions-Short (All)': '18514',
        'Change in Noncommercial-Long (All)': '1765',
        'Change in Noncommercial-Short (All)': '970',
        'Change in Commercial-Long (All)': '-545',
        'Change in Commercial-Short (All)': '58',
        '% of OI-Noncommercial-Long (All)': '70.7',
        '% of OI-Noncommercial-Short (All)': '34.1',
        '% of OI-Commercial-Long (All)': '13.4',
        '% of OI-Commercial-Short (All)': '51.2',
      },
      {
        market: 'U.S. DOLLAR INDEX',
        exchange: 'ICE FUTURES U.S.',
        'Market and Exchange Names': 'U.S. DOLLAR INDEX - ICE FUTURES U.S.',
        'As of Date in Form YYYY-MM-DD': '2020-01-07',
        'Open Interest (All)': '35185',
        'Noncommercial Positions-Long (All)': '23825',
        'Noncommercial Positions-Short (All)': '11357',
        'Commercial Positions-Long (All)': '5383',
        'Commercial Positions-Short (All)': '18456',
        'Change in Noncommercial-Long (All)': '-1121',
        'Change in Noncommercial-Short (All)': '-1534',
        'Change in Commercial-Long (All)': '-598',
        'Change in Commercial-Short (All)': '19',
        '% of OI-Noncommercial-Long (All)': '67.7',
        '% of OI-Noncommercial-Short (All)': '32.3',
        '% of OI-Commercial-Long (All)': '15.3',
        '% of OI-Commercial-Short (All)': '52.5',
      },
    ],
  },
  'CHICAGO MERCANTILE EXCHANGE': {
    '3-MONTH SOFR': [
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-07-07',
        'Open Interest (All)': '150966',
        'Noncommercial Positions-Long (All)': '12144',
        'Noncommercial Positions-Short (All)': '39974',
        'Commercial Positions-Long (All)': '114086',
        'Commercial Positions-Short (All)': '86329',
        'Change in Noncommercial-Long (All)': '383',
        'Change in Noncommercial-Short (All)': '-603',
        'Change in Commercial-Long (All)': '-58',
        'Change in Commercial-Short (All)': '954',
        '% of OI-Noncommercial-Long (All)': '8.0',
        '% of OI-Noncommercial-Short (All)': '26.5',
        '% of OI-Commercial-Long (All)': '75.6',
        '% of OI-Commercial-Short (All)': '57.2',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-30',
        'Open Interest (All)': '151268',
        'Noncommercial Positions-Long (All)': '11761',
        'Noncommercial Positions-Short (All)': '40577',
        'Commercial Positions-Long (All)': '114144',
        'Commercial Positions-Short (All)': '85375',
        'Change in Noncommercial-Long (All)': '31',
        'Change in Noncommercial-Short (All)': '1848',
        'Change in Commercial-Long (All)': '2070',
        'Change in Commercial-Short (All)': '284',
        '% of OI-Noncommercial-Long (All)': '7.8',
        '% of OI-Noncommercial-Short (All)': '26.8',
        '% of OI-Commercial-Long (All)': '75.5',
        '% of OI-Commercial-Short (All)': '56.4',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-23',
        'Open Interest (All)': '151211',
        'Noncommercial Positions-Long (All)': '11730',
        'Noncommercial Positions-Short (All)': '38730',
        'Commercial Positions-Long (All)': '112074',
        'Commercial Positions-Short (All)': '85091',
        'Change in Noncommercial-Long (All)': '-11280',
        'Change in Noncommercial-Short (All)': '-293',
        'Change in Commercial-Long (All)': '-14347',
        'Change in Commercial-Short (All)': '-25335',
        '% of OI-Noncommercial-Long (All)': '7.8',
        '% of OI-Noncommercial-Short (All)': '25.6',
        '% of OI-Commercial-Long (All)': '74.1',
        '% of OI-Commercial-Short (All)': '56.3',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-16',
        'Open Interest (All)': '180222',
        'Noncommercial Positions-Long (All)': '23010',
        'Noncommercial Positions-Short (All)': '39023',
        'Commercial Positions-Long (All)': '126420',
        'Commercial Positions-Short (All)': '110426',
        'Change in Noncommercial-Long (All)': '-2371',
        'Change in Noncommercial-Short (All)': '2506',
        'Change in Commercial-Long (All)': '8398',
        'Change in Commercial-Short (All)': '3492',
        '% of OI-Noncommercial-Long (All)': '12.8',
        '% of OI-Noncommercial-Short (All)': '21.7',
        '% of OI-Commercial-Long (All)': '70.1',
        '% of OI-Commercial-Short (All)': '61.3',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-09',
        'Open Interest (All)': '173349',
        'Noncommercial Positions-Long (All)': '25381',
        'Noncommercial Positions-Short (All)': '36517',
        'Commercial Positions-Long (All)': '118022',
        'Commercial Positions-Short (All)': '106933',
        'Change in Noncommercial-Long (All)': '-6719',
        'Change in Noncommercial-Short (All)': '843',
        'Change in Commercial-Long (All)': '7409',
        'Change in Commercial-Short (All)': '-150',
        '% of OI-Noncommercial-Long (All)': '14.6',
        '% of OI-Noncommercial-Short (All)': '21.1',
        '% of OI-Commercial-Long (All)': '68.1',
        '% of OI-Commercial-Short (All)': '61.7',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-02',
        'Open Interest (All)': '173054',
        'Noncommercial Positions-Long (All)': '32100',
        'Noncommercial Positions-Short (All)': '35674',
        'Commercial Positions-Long (All)': '110614',
        'Commercial Positions-Short (All)': '107083',
        'Change in Noncommercial-Long (All)': '132',
        'Change in Noncommercial-Short (All)': '6874',
        'Change in Commercial-Long (All)': '2256',
        'Change in Commercial-Short (All)': '778',
        '% of OI-Noncommercial-Long (All)': '18.5',
        '% of OI-Noncommercial-Short (All)': '20.6',
        '% of OI-Commercial-Long (All)': '63.9',
        '% of OI-Commercial-Short (All)': '61.9',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-26',
        'Open Interest (All)': '169611',
        'Noncommercial Positions-Long (All)': '31968',
        'Noncommercial Positions-Short (All)': '28800',
        'Commercial Positions-Long (All)': '108358',
        'Commercial Positions-Short (All)': '106305',
        'Change in Noncommercial-Long (All)': '-3388',
        'Change in Noncommercial-Short (All)': '1905',
        'Change in Commercial-Long (All)': '1879',
        'Change in Commercial-Short (All)': '-3899',
        '% of OI-Noncommercial-Long (All)': '18.8',
        '% of OI-Noncommercial-Short (All)': '17.0',
        '% of OI-Commercial-Long (All)': '63.9',
        '% of OI-Commercial-Short (All)': '62.7',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-19',
        'Open Interest (All)': '173568',
        'Noncommercial Positions-Long (All)': '35356',
        'Noncommercial Positions-Short (All)': '26895',
        'Commercial Positions-Long (All)': '106479',
        'Commercial Positions-Short (All)': '110204',
        'Change in Noncommercial-Long (All)': '-614',
        'Change in Noncommercial-Short (All)': '-894',
        'Change in Commercial-Long (All)': '3903',
        'Change in Commercial-Short (All)': '3117',
        '% of OI-Noncommercial-Long (All)': '20.4',
        '% of OI-Noncommercial-Short (All)': '15.5',
        '% of OI-Commercial-Long (All)': '61.3',
        '% of OI-Commercial-Short (All)': '63.5',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-12',
        'Open Interest (All)': '168701',
        'Noncommercial Positions-Long (All)': '35970',
        'Noncommercial Positions-Short (All)': '27789',
        'Commercial Positions-Long (All)': '102576',
        'Commercial Positions-Short (All)': '107088',
        'Change in Noncommercial-Long (All)': '-2662',
        'Change in Noncommercial-Short (All)': '74',
        'Change in Commercial-Long (All)': '7882',
        'Change in Commercial-Short (All)': '5609',
        '% of OI-Noncommercial-Long (All)': '21.3',
        '% of OI-Noncommercial-Short (All)': '16.5',
        '% of OI-Commercial-Long (All)': '60.8',
        '% of OI-Commercial-Short (All)': '63.5',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-05',
        'Open Interest (All)': '160883',
        'Noncommercial Positions-Long (All)': '38632',
        'Noncommercial Positions-Short (All)': '27715',
        'Commercial Positions-Long (All)': '94694',
        'Commercial Positions-Short (All)': '101479',
        'Change in Noncommercial-Long (All)': '2279',
        'Change in Noncommercial-Short (All)': '1207',
        'Change in Commercial-Long (All)': '1270',
        'Change in Commercial-Short (All)': '2333',
        '% of OI-Noncommercial-Long (All)': '24.0',
        '% of OI-Noncommercial-Short (All)': '17.2',
        '% of OI-Commercial-Long (All)': '58.9',
        '% of OI-Commercial-Short (All)': '63.1',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-28',
        'Open Interest (All)': '157285',
        'Noncommercial Positions-Long (All)': '36353',
        'Noncommercial Positions-Short (All)': '26508',
        'Commercial Positions-Long (All)': '93424',
        'Commercial Positions-Short (All)': '99146',
        'Change in Noncommercial-Long (All)': '-1200',
        'Change in Noncommercial-Short (All)': '-373',
        'Change in Commercial-Long (All)': '-826',
        'Change in Commercial-Short (All)': '-1698',
        '% of OI-Noncommercial-Long (All)': '23.1',
        '% of OI-Noncommercial-Short (All)': '16.9',
        '% of OI-Commercial-Long (All)': '59.4',
        '% of OI-Commercial-Short (All)': '63.0',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-21',
        'Open Interest (All)': '156127',
        'Noncommercial Positions-Long (All)': '37553',
        'Noncommercial Positions-Short (All)': '26881',
        'Commercial Positions-Long (All)': '94250',
        'Commercial Positions-Short (All)': '100844',
        'Change in Noncommercial-Long (All)': '969',
        'Change in Noncommercial-Short (All)': '-1658',
        'Change in Commercial-Long (All)': '-1413',
        'Change in Commercial-Short (All)': '-198',
        '% of OI-Noncommercial-Long (All)': '24.1',
        '% of OI-Noncommercial-Short (All)': '17.2',
        '% of OI-Commercial-Long (All)': '60.4',
        '% of OI-Commercial-Short (All)': '64.6',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-14',
        'Open Interest (All)': '157137',
        'Noncommercial Positions-Long (All)': '36584',
        'Noncommercial Positions-Short (All)': '28539',
        'Commercial Positions-Long (All)': '95662',
        'Commercial Positions-Short (All)': '101042',
        'Change in Noncommercial-Long (All)': '1327',
        'Change in Noncommercial-Short (All)': '584',
        'Change in Commercial-Long (All)': '-3067',
        'Change in Commercial-Short (All)': '-2484',
        '% of OI-Noncommercial-Long (All)': '23.3',
        '% of OI-Noncommercial-Short (All)': '18.2',
        '% of OI-Commercial-Long (All)': '60.9',
        '% of OI-Commercial-Short (All)': '64.3',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-07',
        'Open Interest (All)': '159135',
        'Noncommercial Positions-Long (All)': '35257',
        'Noncommercial Positions-Short (All)': '27955',
        'Commercial Positions-Long (All)': '98729',
        'Commercial Positions-Short (All)': '103526',
        'Change in Noncommercial-Long (All)': '-1480',
        'Change in Noncommercial-Short (All)': '-2803',
        'Change in Commercial-Long (All)': '-1892',
        'Change in Commercial-Short (All)': '-577',
        '% of OI-Noncommercial-Long (All)': '22.2',
        '% of OI-Noncommercial-Short (All)': '17.6',
        '% of OI-Commercial-Long (All)': '62.0',
        '% of OI-Commercial-Short (All)': '65.1',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-31',
        'Open Interest (All)': '165708',
        'Noncommercial Positions-Long (All)': '36738',
        'Noncommercial Positions-Short (All)': '30757',
        'Commercial Positions-Long (All)': '100621',
        'Commercial Positions-Short (All)': '104103',
        'Change in Noncommercial-Long (All)': '6195',
        'Change in Noncommercial-Short (All)': '-4399',
        'Change in Commercial-Long (All)': '-3538',
        'Change in Commercial-Short (All)': '5436',
        '% of OI-Noncommercial-Long (All)': '22.2',
        '% of OI-Noncommercial-Short (All)': '18.6',
        '% of OI-Commercial-Long (All)': '60.7',
        '% of OI-Commercial-Short (All)': '62.8',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-24',
        'Open Interest (All)': '171829',
        'Noncommercial Positions-Long (All)': '30543',
        'Noncommercial Positions-Short (All)': '35157',
        'Commercial Positions-Long (All)': '104159',
        'Commercial Positions-Short (All)': '98667',
        'Change in Noncommercial-Long (All)': '-5553',
        'Change in Noncommercial-Short (All)': '-32276',
        'Change in Commercial-Long (All)': '-65378',
        'Change in Commercial-Short (All)': '-36947',
        '% of OI-Noncommercial-Long (All)': '17.8',
        '% of OI-Noncommercial-Short (All)': '20.5',
        '% of OI-Commercial-Long (All)': '60.6',
        '% of OI-Commercial-Short (All)': '57.4',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-17',
        'Open Interest (All)': '245220',
        'Noncommercial Positions-Long (All)': '36096',
        'Noncommercial Positions-Short (All)': '67432',
        'Commercial Positions-Long (All)': '169537',
        'Commercial Positions-Short (All)': '135614',
        'Change in Noncommercial-Long (All)': '6130',
        'Change in Noncommercial-Short (All)': '13801',
        'Change in Commercial-Long (All)': '9426',
        'Change in Commercial-Short (All)': '1952',
        '% of OI-Noncommercial-Long (All)': '14.7',
        '% of OI-Noncommercial-Short (All)': '27.5',
        '% of OI-Commercial-Long (All)': '69.1',
        '% of OI-Commercial-Short (All)': '55.3',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-10',
        'Open Interest (All)': '232729',
        'Noncommercial Positions-Long (All)': '29966',
        'Noncommercial Positions-Short (All)': '53631',
        'Commercial Positions-Long (All)': '160111',
        'Commercial Positions-Short (All)': '133662',
        'Change in Noncommercial-Long (All)': '-7309',
        'Change in Noncommercial-Short (All)': '5377',
        'Change in Commercial-Long (All)': '30391',
        'Change in Commercial-Short (All)': '16644',
        '% of OI-Noncommercial-Long (All)': '12.9',
        '% of OI-Noncommercial-Short (All)': '23.0',
        '% of OI-Commercial-Long (All)': '68.8',
        '% of OI-Commercial-Short (All)': '57.4',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-03',
        'Open Interest (All)': '209600',
        'Noncommercial Positions-Long (All)': '37275',
        'Noncommercial Positions-Short (All)': '48254',
        'Commercial Positions-Long (All)': '129720',
        'Commercial Positions-Short (All)': '117018',
        'Change in Noncommercial-Long (All)': '16555',
        'Change in Noncommercial-Short (All)': '14790',
        'Change in Commercial-Long (All)': '9192',
        'Change in Commercial-Short (All)': '11177',
        '% of OI-Noncommercial-Long (All)': '17.8',
        '% of OI-Noncommercial-Short (All)': '23.0',
        '% of OI-Commercial-Long (All)': '61.9',
        '% of OI-Commercial-Short (All)': '55.8',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-25',
        'Open Interest (All)': '177626',
        'Noncommercial Positions-Long (All)': '20720',
        'Noncommercial Positions-Short (All)': '33464',
        'Commercial Positions-Long (All)': '120528',
        'Commercial Positions-Short (All)': '105841',
        'Change in Noncommercial-Long (All)': '3940',
        'Change in Noncommercial-Short (All)': '14098',
        'Change in Commercial-Long (All)': '9676',
        'Change in Commercial-Short (All)': '-550',
        '% of OI-Noncommercial-Long (All)': '11.7',
        '% of OI-Noncommercial-Short (All)': '18.8',
        '% of OI-Commercial-Long (All)': '67.9',
        '% of OI-Commercial-Short (All)': '59.6',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-18',
        'Open Interest (All)': '170487',
        'Noncommercial Positions-Long (All)': '16780',
        'Noncommercial Positions-Short (All)': '19366',
        'Commercial Positions-Long (All)': '110852',
        'Commercial Positions-Short (All)': '106391',
        'Change in Noncommercial-Long (All)': '289',
        'Change in Noncommercial-Short (All)': '376',
        'Change in Commercial-Long (All)': '1124',
        'Change in Commercial-Short (All)': '-580',
        '% of OI-Noncommercial-Long (All)': '9.8',
        '% of OI-Noncommercial-Short (All)': '11.4',
        '% of OI-Commercial-Long (All)': '65.0',
        '% of OI-Commercial-Short (All)': '62.4',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-11',
        'Open Interest (All)': '167664',
        'Noncommercial Positions-Long (All)': '16491',
        'Noncommercial Positions-Short (All)': '18990',
        'Commercial Positions-Long (All)': '109728',
        'Commercial Positions-Short (All)': '106971',
        'Change in Noncommercial-Long (All)': '-7989',
        'Change in Noncommercial-Short (All)': '-2190',
        'Change in Commercial-Long (All)': '10454',
        'Change in Commercial-Short (All)': '4637',
        '% of OI-Noncommercial-Long (All)': '9.8',
        '% of OI-Noncommercial-Short (All)': '11.3',
        '% of OI-Commercial-Long (All)': '65.4',
        '% of OI-Commercial-Short (All)': '63.8',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-04',
        'Open Interest (All)': '153153',
        'Noncommercial Positions-Long (All)': '24480',
        'Noncommercial Positions-Short (All)': '21180',
        'Commercial Positions-Long (All)': '99274',
        'Commercial Positions-Short (All)': '102334',
        'Change in Noncommercial-Long (All)': '-3137',
        'Change in Noncommercial-Short (All)': '1274',
        'Change in Commercial-Long (All)': '6042',
        'Change in Commercial-Short (All)': '1511',
        '% of OI-Noncommercial-Long (All)': '16.0',
        '% of OI-Noncommercial-Short (All)': '13.8',
        '% of OI-Commercial-Long (All)': '64.8',
        '% of OI-Commercial-Short (All)': '66.8',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-28',
        'Open Interest (All)': '154537',
        'Noncommercial Positions-Long (All)': '27617',
        'Noncommercial Positions-Short (All)': '19906',
        'Commercial Positions-Long (All)': '93232',
        'Commercial Positions-Short (All)': '100824',
        'Change in Noncommercial-Long (All)': '10',
        'Change in Noncommercial-Short (All)': '3145',
        'Change in Commercial-Long (All)': '11383',
        'Change in Commercial-Short (All)': '8161',
        '% of OI-Noncommercial-Long (All)': '17.9',
        '% of OI-Noncommercial-Short (All)': '12.9',
        '% of OI-Commercial-Long (All)': '60.3',
        '% of OI-Commercial-Short (All)': '65.2',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-21',
        'Open Interest (All)': '141412',
        'Noncommercial Positions-Long (All)': '27607',
        'Noncommercial Positions-Short (All)': '16761',
        'Commercial Positions-Long (All)': '81849',
        'Commercial Positions-Short (All)': '92662',
        'Change in Noncommercial-Long (All)': '-540',
        'Change in Noncommercial-Short (All)': '2928',
        'Change in Commercial-Long (All)': '8353',
        'Change in Commercial-Short (All)': '4788',
        '% of OI-Noncommercial-Long (All)': '19.5',
        '% of OI-Noncommercial-Short (All)': '11.9',
        '% of OI-Commercial-Long (All)': '57.9',
        '% of OI-Commercial-Short (All)': '65.5',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-14',
        'Open Interest (All)': '135911',
        'Noncommercial Positions-Long (All)': '28147',
        'Noncommercial Positions-Short (All)': '13833',
        'Commercial Positions-Long (All)': '73496',
        'Commercial Positions-Short (All)': '87874',
        'Change in Noncommercial-Long (All)': '-467',
        'Change in Noncommercial-Short (All)': '1636',
        'Change in Commercial-Long (All)': '2679',
        'Change in Commercial-Short (All)': '-563',
        '% of OI-Noncommercial-Long (All)': '20.7',
        '% of OI-Noncommercial-Short (All)': '10.2',
        '% of OI-Commercial-Long (All)': '54.1',
        '% of OI-Commercial-Short (All)': '64.7',
      },
      {
        market: '3-MONTH SOFR',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          '3-MONTH SOFR - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-07',
        'Open Interest (All)': '131481',
        'Noncommercial Positions-Long (All)': '28614',
        'Noncommercial Positions-Short (All)': '12197',
        'Commercial Positions-Long (All)': '70817',
        'Commercial Positions-Short (All)': '88437',
        'Change in Noncommercial-Long (All)': '647',
        'Change in Noncommercial-Short (All)': '-726',
        'Change in Commercial-Long (All)': '1058',
        'Change in Commercial-Short (All)': '2541',
        '% of OI-Noncommercial-Long (All)': '21.8',
        '% of OI-Noncommercial-Short (All)': '9.3',
        '% of OI-Commercial-Long (All)': '53.9',
        '% of OI-Commercial-Short (All)': '67.3',
      },
    ],
    'EURO FX': [
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-07-07',
        'Open Interest (All)': '646323',
        'Noncommercial Positions-Long (All)': '186241',
        'Noncommercial Positions-Short (All)': '80047',
        'Commercial Positions-Long (All)': '331247',
        'Commercial Positions-Short (All)': '489461',
        'Change in Noncommercial-Long (All)': '5904',
        'Change in Noncommercial-Short (All)': '1730',
        'Change in Commercial-Long (All)': '526',
        'Change in Commercial-Short (All)': '7560',
        '% of OI-Noncommercial-Long (All)': '28.8',
        '% of OI-Noncommercial-Short (All)': '12.4',
        '% of OI-Commercial-Long (All)': '51.3',
        '% of OI-Commercial-Short (All)': '75.7',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-30',
        'Open Interest (All)': '643597',
        'Noncommercial Positions-Long (All)': '180338',
        'Noncommercial Positions-Short (All)': '78317',
        'Commercial Positions-Long (All)': '330721',
        'Commercial Positions-Short (All)': '481901',
        'Change in Noncommercial-Long (All)': '-10929',
        'Change in Noncommercial-Short (All)': '6403',
        'Change in Commercial-Long (All)': '919',
        'Change in Commercial-Short (All)': '-11152',
        '% of OI-Noncommercial-Long (All)': '28.0',
        '% of OI-Noncommercial-Short (All)': '12.2',
        '% of OI-Commercial-Long (All)': '51.4',
        '% of OI-Commercial-Short (All)': '74.9',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-23',
        'Open Interest (All)': '648743',
        'Noncommercial Positions-Long (All)': '191267',
        'Noncommercial Positions-Short (All)': '71914',
        'Commercial Positions-Long (All)': '329802',
        'Commercial Positions-Short (All)': '493053',
        'Change in Noncommercial-Long (All)': '3162',
        'Change in Noncommercial-Short (All)': '2053',
        'Change in Commercial-Long (All)': '2766',
        'Change in Commercial-Short (All)': '10795',
        '% of OI-Noncommercial-Long (All)': '29.5',
        '% of OI-Noncommercial-Short (All)': '11.1',
        '% of OI-Commercial-Long (All)': '50.8',
        '% of OI-Commercial-Short (All)': '76.0',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-16',
        'Open Interest (All)': '637313',
        'Noncommercial Positions-Long (All)': '188105',
        'Noncommercial Positions-Short (All)': '69861',
        'Commercial Positions-Long (All)': '327036',
        'Commercial Positions-Short (All)': '482258',
        'Change in Noncommercial-Long (All)': '1305',
        'Change in Noncommercial-Short (All)': '-19391',
        'Change in Commercial-Long (All)': '-12421',
        'Change in Commercial-Short (All)': '7783',
        '% of OI-Noncommercial-Long (All)': '29.5',
        '% of OI-Noncommercial-Short (All)': '11.0',
        '% of OI-Commercial-Long (All)': '51.3',
        '% of OI-Commercial-Short (All)': '75.7',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-09',
        'Open Interest (All)': '655042',
        'Noncommercial Positions-Long (All)': '186800',
        'Noncommercial Positions-Short (All)': '89251',
        'Commercial Positions-Long (All)': '339457',
        'Commercial Positions-Short (All)': '474476',
        'Change in Noncommercial-Long (All)': '12662',
        'Change in Noncommercial-Short (All)': '-2579',
        'Change in Commercial-Long (All)': '4100',
        'Change in Commercial-Short (All)': '20766',
        '% of OI-Noncommercial-Long (All)': '28.5',
        '% of OI-Noncommercial-Short (All)': '13.6',
        '% of OI-Commercial-Long (All)': '51.8',
        '% of OI-Commercial-Short (All)': '72.4',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-02',
        'Open Interest (All)': '648551',
        'Noncommercial Positions-Long (All)': '174138',
        'Noncommercial Positions-Short (All)': '91831',
        'Commercial Positions-Long (All)': '335358',
        'Commercial Positions-Short (All)': '453710',
        'Change in Noncommercial-Long (All)': '-105',
        'Change in Noncommercial-Short (All)': '-5732',
        'Change in Commercial-Long (All)': '19793',
        'Change in Commercial-Short (All)': '29935',
        '% of OI-Noncommercial-Long (All)': '26.9',
        '% of OI-Noncommercial-Short (All)': '14.2',
        '% of OI-Commercial-Long (All)': '51.7',
        '% of OI-Commercial-Short (All)': '70.0',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-26',
        'Open Interest (All)': '609350',
        'Noncommercial Positions-Long (All)': '174243',
        'Noncommercial Positions-Short (All)': '97562',
        'Commercial Positions-Long (All)': '315565',
        'Commercial Positions-Short (All)': '423775',
        'Change in Noncommercial-Long (All)': '7524',
        'Change in Noncommercial-Short (All)': '3817',
        'Change in Commercial-Long (All)': '1030',
        'Change in Commercial-Short (All)': '6493',
        '% of OI-Noncommercial-Long (All)': '28.6',
        '% of OI-Noncommercial-Short (All)': '16.0',
        '% of OI-Commercial-Long (All)': '51.8',
        '% of OI-Commercial-Short (All)': '69.5',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-19',
        'Open Interest (All)': '601044',
        'Noncommercial Positions-Long (All)': '166719',
        'Noncommercial Positions-Short (All)': '93745',
        'Commercial Positions-Long (All)': '314535',
        'Commercial Positions-Short (All)': '417282',
        'Change in Noncommercial-Long (All)': '-3425',
        'Change in Noncommercial-Short (All)': '1257',
        'Change in Commercial-Long (All)': '1490',
        'Change in Commercial-Short (All)': '-1928',
        '% of OI-Noncommercial-Long (All)': '27.7',
        '% of OI-Noncommercial-Short (All)': '15.6',
        '% of OI-Commercial-Long (All)': '52.3',
        '% of OI-Commercial-Short (All)': '69.4',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-12',
        'Open Interest (All)': '598612',
        'Noncommercial Positions-Long (All)': '170143',
        'Noncommercial Positions-Short (All)': '92488',
        'Commercial Positions-Long (All)': '313045',
        'Commercial Positions-Short (All)': '419210',
        'Change in Noncommercial-Long (All)': '4569',
        'Change in Noncommercial-Short (All)': '886',
        'Change in Commercial-Long (All)': '-1787',
        'Change in Commercial-Short (All)': '3134',
        '% of OI-Noncommercial-Long (All)': '28.4',
        '% of OI-Noncommercial-Short (All)': '15.5',
        '% of OI-Commercial-Long (All)': '52.3',
        '% of OI-Commercial-Short (All)': '70.0',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-05',
        'Open Interest (All)': '605228',
        'Noncommercial Positions-Long (All)': '165575',
        'Noncommercial Positions-Short (All)': '91602',
        'Commercial Positions-Long (All)': '314832',
        'Commercial Positions-Short (All)': '416077',
        'Change in Noncommercial-Long (All)': '763',
        'Change in Noncommercial-Short (All)': '5891',
        'Change in Commercial-Long (All)': '148',
        'Change in Commercial-Short (All)': '-6271',
        '% of OI-Noncommercial-Long (All)': '27.4',
        '% of OI-Noncommercial-Short (All)': '15.1',
        '% of OI-Commercial-Long (All)': '52.0',
        '% of OI-Commercial-Short (All)': '68.7',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-28',
        'Open Interest (All)': '608104',
        'Noncommercial Positions-Long (All)': '164811',
        'Noncommercial Positions-Short (All)': '85712',
        'Commercial Positions-Long (All)': '314685',
        'Commercial Positions-Short (All)': '422348',
        'Change in Noncommercial-Long (All)': '-4256',
        'Change in Noncommercial-Short (All)': '3182',
        'Change in Commercial-Long (All)': '-6001',
        'Change in Commercial-Short (All)': '-13207',
        '% of OI-Noncommercial-Long (All)': '27.1',
        '% of OI-Noncommercial-Short (All)': '14.1',
        '% of OI-Commercial-Long (All)': '51.7',
        '% of OI-Commercial-Short (All)': '69.5',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-21',
        'Open Interest (All)': '608534',
        'Noncommercial Positions-Long (All)': '169068',
        'Noncommercial Positions-Short (All)': '82530',
        'Commercial Positions-Long (All)': '320686',
        'Commercial Positions-Short (All)': '435554',
        'Change in Noncommercial-Long (All)': '5425',
        'Change in Noncommercial-Short (All)': '4086',
        'Change in Commercial-Long (All)': '1659',
        'Change in Commercial-Short (All)': '-3197',
        '% of OI-Noncommercial-Long (All)': '27.8',
        '% of OI-Noncommercial-Short (All)': '13.6',
        '% of OI-Commercial-Long (All)': '52.7',
        '% of OI-Commercial-Short (All)': '71.6',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-14',
        'Open Interest (All)': '600593',
        'Noncommercial Positions-Long (All)': '163643',
        'Noncommercial Positions-Short (All)': '78444',
        'Commercial Positions-Long (All)': '319028',
        'Commercial Positions-Short (All)': '438751',
        'Change in Noncommercial-Long (All)': '2440',
        'Change in Noncommercial-Short (All)': '-4657',
        'Change in Commercial-Long (All)': '-8322',
        'Change in Commercial-Short (All)': '-5392',
        '% of OI-Noncommercial-Long (All)': '27.2',
        '% of OI-Noncommercial-Short (All)': '13.1',
        '% of OI-Commercial-Long (All)': '53.1',
        '% of OI-Commercial-Short (All)': '73.1',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-07',
        'Open Interest (All)': '615155',
        'Noncommercial Positions-Long (All)': '161204',
        'Noncommercial Positions-Short (All)': '83102',
        'Commercial Positions-Long (All)': '327350',
        'Commercial Positions-Short (All)': '444143',
        'Change in Noncommercial-Long (All)': '6022',
        'Change in Noncommercial-Short (All)': '832',
        'Change in Commercial-Long (All)': '-22576',
        'Change in Commercial-Short (All)': '-6043',
        '% of OI-Noncommercial-Long (All)': '26.2',
        '% of OI-Noncommercial-Short (All)': '13.5',
        '% of OI-Commercial-Long (All)': '53.2',
        '% of OI-Commercial-Short (All)': '72.2',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-31',
        'Open Interest (All)': '634755',
        'Noncommercial Positions-Long (All)': '155182',
        'Noncommercial Positions-Short (All)': '82269',
        'Commercial Positions-Long (All)': '349926',
        'Commercial Positions-Short (All)': '450186',
        'Change in Noncommercial-Long (All)': '5445',
        'Change in Noncommercial-Short (All)': '-11733',
        'Change in Commercial-Long (All)': '-18994',
        'Change in Commercial-Short (All)': '-2848',
        '% of OI-Noncommercial-Long (All)': '24.4',
        '% of OI-Noncommercial-Short (All)': '13.0',
        '% of OI-Commercial-Long (All)': '55.1',
        '% of OI-Commercial-Short (All)': '70.9',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-24',
        'Open Interest (All)': '666348',
        'Noncommercial Positions-Long (All)': '149736',
        'Noncommercial Positions-Short (All)': '94002',
        'Commercial Positions-Long (All)': '368920',
        'Commercial Positions-Short (All)': '453033',
        'Change in Noncommercial-Long (All)': '1583',
        'Change in Noncommercial-Short (All)': '-23066',
        'Change in Commercial-Long (All)': '-24762',
        'Change in Commercial-Short (All)': '-7055',
        '% of OI-Noncommercial-Long (All)': '22.5',
        '% of OI-Noncommercial-Short (All)': '14.1',
        '% of OI-Commercial-Long (All)': '55.4',
        '% of OI-Commercial-Short (All)': '68.0',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-17',
        'Open Interest (All)': '680940',
        'Noncommercial Positions-Long (All)': '148153',
        'Noncommercial Positions-Short (All)': '117068',
        'Commercial Positions-Long (All)': '393682',
        'Commercial Positions-Short (All)': '460088',
        'Change in Noncommercial-Long (All)': '-4126',
        'Change in Noncommercial-Short (All)': '-47647',
        'Change in Commercial-Long (All)': '-47825',
        'Change in Commercial-Short (All)': '-10105',
        '% of OI-Noncommercial-Long (All)': '21.8',
        '% of OI-Noncommercial-Short (All)': '17.2',
        '% of OI-Commercial-Long (All)': '57.8',
        '% of OI-Commercial-Short (All)': '67.6',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-10',
        'Open Interest (All)': '754022',
        'Noncommercial Positions-Long (All)': '152279',
        'Noncommercial Positions-Short (All)': '164716',
        'Commercial Positions-Long (All)': '441507',
        'Commercial Positions-Short (All)': '470193',
        'Change in Noncommercial-Long (All)': '-868',
        'Change in Noncommercial-Short (All)': '-72432',
        'Change in Commercial-Long (All)': '2416',
        'Change in Commercial-Short (All)': '88247',
        '% of OI-Noncommercial-Long (All)': '20.2',
        '% of OI-Noncommercial-Short (All)': '21.8',
        '% of OI-Commercial-Long (All)': '58.6',
        '% of OI-Commercial-Short (All)': '62.4',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-03',
        'Open Interest (All)': '752287',
        'Noncommercial Positions-Long (All)': '153147',
        'Noncommercial Positions-Short (All)': '237148',
        'Commercial Positions-Long (All)': '439092',
        'Commercial Positions-Short (All)': '381946',
        'Change in Noncommercial-Long (All)': '-324',
        'Change in Noncommercial-Short (All)': '-40089',
        'Change in Commercial-Long (All)': '40794',
        'Change in Commercial-Short (All)': '75632',
        '% of OI-Noncommercial-Long (All)': '20.4',
        '% of OI-Noncommercial-Short (All)': '31.5',
        '% of OI-Commercial-Long (All)': '58.4',
        '% of OI-Commercial-Short (All)': '50.8',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-25',
        'Open Interest (All)': '710390',
        'Noncommercial Positions-Long (All)': '153472',
        'Noncommercial Positions-Short (All)': '277237',
        'Commercial Positions-Long (All)': '398298',
        'Commercial Positions-Short (All)': '306313',
        'Change in Noncommercial-Long (All)': '-15222',
        'Change in Noncommercial-Short (All)': '6681',
        'Change in Commercial-Long (All)': '19445',
        'Change in Commercial-Short (All)': '-8249',
        '% of OI-Noncommercial-Long (All)': '21.6',
        '% of OI-Noncommercial-Short (All)': '39.0',
        '% of OI-Commercial-Long (All)': '56.1',
        '% of OI-Commercial-Short (All)': '43.1',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-18',
        'Open Interest (All)': '696623',
        'Noncommercial Positions-Long (All)': '168693',
        'Noncommercial Positions-Short (All)': '270555',
        'Commercial Positions-Long (All)': '378852',
        'Commercial Positions-Short (All)': '314562',
        'Change in Noncommercial-Long (All)': '313',
        'Change in Noncommercial-Short (All)': '10686',
        'Change in Commercial-Long (All)': '11962',
        'Change in Commercial-Short (All)': '7273',
        '% of OI-Noncommercial-Long (All)': '24.2',
        '% of OI-Noncommercial-Short (All)': '38.8',
        '% of OI-Commercial-Long (All)': '54.4',
        '% of OI-Commercial-Short (All)': '45.2',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-11',
        'Open Interest (All)': '672682',
        'Noncommercial Positions-Long (All)': '168381',
        'Noncommercial Positions-Short (All)': '259869',
        'Commercial Positions-Long (All)': '366890',
        'Commercial Positions-Short (All)': '307289',
        'Change in Noncommercial-Long (All)': '682',
        'Change in Noncommercial-Short (All)': '12193',
        'Change in Commercial-Long (All)': '20622',
        'Change in Commercial-Short (All)': '2146',
        '% of OI-Noncommercial-Long (All)': '25.0',
        '% of OI-Noncommercial-Short (All)': '38.6',
        '% of OI-Commercial-Long (All)': '54.5',
        '% of OI-Commercial-Short (All)': '45.7',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-04',
        'Open Interest (All)': '651676',
        'Noncommercial Positions-Long (All)': '167699',
        'Noncommercial Positions-Short (All)': '247676',
        'Commercial Positions-Long (All)': '346268',
        'Commercial Positions-Short (All)': '305143',
        'Change in Noncommercial-Long (All)': '-10186',
        'Change in Noncommercial-Short (All)': '3693',
        'Change in Commercial-Long (All)': '9182',
        'Change in Commercial-Short (All)': '-6692',
        '% of OI-Noncommercial-Long (All)': '25.7',
        '% of OI-Noncommercial-Short (All)': '38.0',
        '% of OI-Commercial-Long (All)': '53.1',
        '% of OI-Commercial-Short (All)': '46.8',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-28',
        'Open Interest (All)': '655157',
        'Noncommercial Positions-Long (All)': '177885',
        'Noncommercial Positions-Short (All)': '243983',
        'Commercial Positions-Long (All)': '337086',
        'Commercial Positions-Short (All)': '311836',
        'Change in Noncommercial-Long (All)': '12606',
        'Change in Noncommercial-Short (All)': '26679',
        'Change in Commercial-Long (All)': '14134',
        'Change in Commercial-Short (All)': '-329',
        '% of OI-Noncommercial-Long (All)': '27.2',
        '% of OI-Noncommercial-Short (All)': '37.2',
        '% of OI-Commercial-Long (All)': '51.5',
        '% of OI-Commercial-Short (All)': '47.6',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-21',
        'Open Interest (All)': '627893',
        'Noncommercial Positions-Long (All)': '165279',
        'Noncommercial Positions-Short (All)': '217304',
        'Commercial Positions-Long (All)': '322952',
        'Commercial Positions-Short (All)': '312165',
        'Change in Noncommercial-Long (All)': '3396',
        'Change in Noncommercial-Short (All)': '2873',
        'Change in Commercial-Long (All)': '5776',
        'Change in Commercial-Short (All)': '6865',
        '% of OI-Noncommercial-Long (All)': '26.3',
        '% of OI-Noncommercial-Short (All)': '34.6',
        '% of OI-Commercial-Long (All)': '51.4',
        '% of OI-Commercial-Short (All)': '49.7',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-14',
        'Open Interest (All)': '614421',
        'Noncommercial Positions-Long (All)': '161883',
        'Noncommercial Positions-Short (All)': '214431',
        'Commercial Positions-Long (All)': '317176',
        'Commercial Positions-Short (All)': '305300',
        'Change in Noncommercial-Long (All)': '-2134',
        'Change in Noncommercial-Short (All)': '-14275',
        'Change in Commercial-Long (All)': '11436',
        'Change in Commercial-Short (All)': '27005',
        '% of OI-Noncommercial-Long (All)': '26.3',
        '% of OI-Noncommercial-Short (All)': '34.9',
        '% of OI-Commercial-Long (All)': '51.6',
        '% of OI-Commercial-Short (All)': '49.7',
      },
      {
        market: 'EURO FX',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names': 'EURO FX - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-07',
        'Open Interest (All)': '597223',
        'Noncommercial Positions-Long (All)': '164017',
        'Noncommercial Positions-Short (All)': '228706',
        'Commercial Positions-Long (All)': '305740',
        'Commercial Positions-Short (All)': '278296',
        'Change in Noncommercial-Long (All)': '-1827',
        'Change in Noncommercial-Short (All)': '-12365',
        'Change in Commercial-Long (All)': '-3133',
        'Change in Commercial-Short (All)': '9072',
        '% of OI-Noncommercial-Long (All)': '27.5',
        '% of OI-Noncommercial-Short (All)': '38.3',
        '% of OI-Commercial-Long (All)': '51.2',
        '% of OI-Commercial-Short (All)': '46.6',
      },
    ],
    'EURO FX/BRITISH POUND XRATE': [
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-07-07',
        'Open Interest (All)': '23701',
        'Noncommercial Positions-Long (All)': '3357',
        'Noncommercial Positions-Short (All)': '3518',
        'Commercial Positions-Long (All)': '7552',
        'Commercial Positions-Short (All)': '15128',
        'Change in Noncommercial-Long (All)': '-919',
        'Change in Noncommercial-Short (All)': '-1506',
        'Change in Commercial-Long (All)': '244',
        'Change in Commercial-Short (All)': '722',
        '% of OI-Noncommercial-Long (All)': '14.2',
        '% of OI-Noncommercial-Short (All)': '14.8',
        '% of OI-Commercial-Long (All)': '31.9',
        '% of OI-Commercial-Short (All)': '63.8',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-30',
        'Open Interest (All)': '24041',
        'Noncommercial Positions-Long (All)': '4276',
        'Noncommercial Positions-Short (All)': '5024',
        'Commercial Positions-Long (All)': '7308',
        'Commercial Positions-Short (All)': '14406',
        'Change in Noncommercial-Long (All)': '753',
        'Change in Noncommercial-Short (All)': '-101',
        'Change in Commercial-Long (All)': '-26',
        'Change in Commercial-Short (All)': '447',
        '% of OI-Noncommercial-Long (All)': '17.8',
        '% of OI-Noncommercial-Short (All)': '20.9',
        '% of OI-Commercial-Long (All)': '30.4',
        '% of OI-Commercial-Short (All)': '59.9',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-23',
        'Open Interest (All)': '23511',
        'Noncommercial Positions-Long (All)': '3523',
        'Noncommercial Positions-Short (All)': '5125',
        'Commercial Positions-Long (All)': '7334',
        'Commercial Positions-Short (All)': '13959',
        'Change in Noncommercial-Long (All)': '77',
        'Change in Noncommercial-Short (All)': '446',
        'Change in Commercial-Long (All)': '134',
        'Change in Commercial-Short (All)': '52',
        '% of OI-Noncommercial-Long (All)': '15.0',
        '% of OI-Noncommercial-Short (All)': '21.8',
        '% of OI-Commercial-Long (All)': '31.2',
        '% of OI-Commercial-Short (All)': '59.4',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-16',
        'Open Interest (All)': '23236',
        'Noncommercial Positions-Long (All)': '3446',
        'Noncommercial Positions-Short (All)': '4679',
        'Commercial Positions-Long (All)': '7200',
        'Commercial Positions-Short (All)': '13907',
        'Change in Noncommercial-Long (All)': '494',
        'Change in Noncommercial-Short (All)': '331',
        'Change in Commercial-Long (All)': '37',
        'Change in Commercial-Short (All)': '-886',
        '% of OI-Noncommercial-Long (All)': '14.8',
        '% of OI-Noncommercial-Short (All)': '20.1',
        '% of OI-Commercial-Long (All)': '31.0',
        '% of OI-Commercial-Short (All)': '59.9',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-09',
        'Open Interest (All)': '25066',
        'Noncommercial Positions-Long (All)': '2952',
        'Noncommercial Positions-Short (All)': '4348',
        'Commercial Positions-Long (All)': '7163',
        'Commercial Positions-Short (All)': '14793',
        'Change in Noncommercial-Long (All)': '-305',
        'Change in Noncommercial-Short (All)': '609',
        'Change in Commercial-Long (All)': '-58',
        'Change in Commercial-Short (All)': '-28',
        '% of OI-Noncommercial-Long (All)': '11.8',
        '% of OI-Noncommercial-Short (All)': '17.3',
        '% of OI-Commercial-Long (All)': '28.6',
        '% of OI-Commercial-Short (All)': '59.0',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-06-02',
        'Open Interest (All)': '23212',
        'Noncommercial Positions-Long (All)': '3257',
        'Noncommercial Positions-Short (All)': '3739',
        'Commercial Positions-Long (All)': '7221',
        'Commercial Positions-Short (All)': '14821',
        'Change in Noncommercial-Long (All)': '335',
        'Change in Noncommercial-Short (All)': '86',
        'Change in Commercial-Long (All)': '158',
        'Change in Commercial-Short (All)': '135',
        '% of OI-Noncommercial-Long (All)': '14.0',
        '% of OI-Noncommercial-Short (All)': '16.1',
        '% of OI-Commercial-Long (All)': '31.1',
        '% of OI-Commercial-Short (All)': '63.9',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-05-26',
        'Open Interest (All)': '22871',
        'Noncommercial Positions-Long (All)': '2922',
        'Noncommercial Positions-Short (All)': '3653',
        'Commercial Positions-Long (All)': '7063',
        'Commercial Positions-Short (All)': '14686',
        'Change in Noncommercial-Long (All)': '.',
        'Change in Noncommercial-Short (All)': '.',
        'Change in Commercial-Long (All)': '.',
        'Change in Commercial-Short (All)': '.',
        '% of OI-Noncommercial-Long (All)': '12.8',
        '% of OI-Noncommercial-Short (All)': '16.0',
        '% of OI-Commercial-Long (All)': '30.9',
        '% of OI-Commercial-Short (All)': '64.2',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-28',
        'Open Interest (All)': '22091',
        'Noncommercial Positions-Long (All)': '3274',
        'Noncommercial Positions-Short (All)': '2571',
        'Commercial Positions-Long (All)': '6920',
        'Commercial Positions-Short (All)': '15229',
        'Change in Noncommercial-Long (All)': '-67',
        'Change in Noncommercial-Short (All)': '-332',
        'Change in Commercial-Long (All)': '673',
        'Change in Commercial-Short (All)': '0',
        '% of OI-Noncommercial-Long (All)': '14.8',
        '% of OI-Noncommercial-Short (All)': '11.6',
        '% of OI-Commercial-Long (All)': '31.3',
        '% of OI-Commercial-Short (All)': '68.9',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-21',
        'Open Interest (All)': '22171',
        'Noncommercial Positions-Long (All)': '3341',
        'Noncommercial Positions-Short (All)': '2903',
        'Commercial Positions-Long (All)': '6247',
        'Commercial Positions-Short (All)': '15229',
        'Change in Noncommercial-Long (All)': '-111',
        'Change in Noncommercial-Short (All)': '795',
        'Change in Commercial-Long (All)': '96',
        'Change in Commercial-Short (All)': '-4',
        '% of OI-Noncommercial-Long (All)': '15.1',
        '% of OI-Noncommercial-Short (All)': '13.1',
        '% of OI-Commercial-Long (All)': '28.2',
        '% of OI-Commercial-Short (All)': '68.7',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-14',
        'Open Interest (All)': '21205',
        'Noncommercial Positions-Long (All)': '3452',
        'Noncommercial Positions-Short (All)': '2108',
        'Commercial Positions-Long (All)': '6151',
        'Commercial Positions-Short (All)': '15233',
        'Change in Noncommercial-Long (All)': '79',
        'Change in Noncommercial-Short (All)': '-372',
        'Change in Commercial-Long (All)': '36',
        'Change in Commercial-Short (All)': '-5',
        '% of OI-Noncommercial-Long (All)': '16.3',
        '% of OI-Noncommercial-Short (All)': '9.9',
        '% of OI-Commercial-Long (All)': '29.0',
        '% of OI-Commercial-Short (All)': '71.8',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-04-07',
        'Open Interest (All)': '21364',
        'Noncommercial Positions-Long (All)': '3373',
        'Noncommercial Positions-Short (All)': '2480',
        'Commercial Positions-Long (All)': '6115',
        'Commercial Positions-Short (All)': '15238',
        'Change in Noncommercial-Long (All)': '.',
        'Change in Noncommercial-Short (All)': '.',
        'Change in Commercial-Long (All)': '.',
        'Change in Commercial-Short (All)': '.',
        '% of OI-Noncommercial-Long (All)': '15.8',
        '% of OI-Noncommercial-Short (All)': '11.6',
        '% of OI-Commercial-Long (All)': '28.6',
        '% of OI-Commercial-Short (All)': '71.3',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-03-10',
        'Open Interest (All)': '23628',
        'Noncommercial Positions-Long (All)': '3549',
        'Noncommercial Positions-Short (All)': '5488',
        'Commercial Positions-Long (All)': '6396',
        'Commercial Positions-Short (All)': '11951',
        'Change in Noncommercial-Long (All)': '.',
        'Change in Noncommercial-Short (All)': '.',
        'Change in Commercial-Long (All)': '.',
        'Change in Commercial-Short (All)': '.',
        '% of OI-Noncommercial-Long (All)': '15.0',
        '% of OI-Noncommercial-Short (All)': '23.2',
        '% of OI-Commercial-Long (All)': '27.1',
        '% of OI-Commercial-Short (All)': '50.6',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-25',
        'Open Interest (All)': '23419',
        'Noncommercial Positions-Long (All)': '3343',
        'Noncommercial Positions-Short (All)': '3653',
        'Commercial Positions-Long (All)': '6503',
        'Commercial Positions-Short (All)': '12022',
        'Change in Noncommercial-Long (All)': '-15',
        'Change in Noncommercial-Short (All)': '-159',
        'Change in Commercial-Long (All)': '-570',
        'Change in Commercial-Short (All)': '-94',
        '% of OI-Noncommercial-Long (All)': '14.3',
        '% of OI-Noncommercial-Short (All)': '15.6',
        '% of OI-Commercial-Long (All)': '27.8',
        '% of OI-Commercial-Short (All)': '51.3',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-18',
        'Open Interest (All)': '23860',
        'Noncommercial Positions-Long (All)': '3358',
        'Noncommercial Positions-Short (All)': '3812',
        'Commercial Positions-Long (All)': '7073',
        'Commercial Positions-Short (All)': '12116',
        'Change in Noncommercial-Long (All)': '8',
        'Change in Noncommercial-Short (All)': '-219',
        'Change in Commercial-Long (All)': '-228',
        'Change in Commercial-Short (All)': '64',
        '% of OI-Noncommercial-Long (All)': '14.1',
        '% of OI-Noncommercial-Short (All)': '16.0',
        '% of OI-Commercial-Long (All)': '29.6',
        '% of OI-Commercial-Short (All)': '50.8',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-11',
        'Open Interest (All)': '23488',
        'Noncommercial Positions-Long (All)': '3350',
        'Noncommercial Positions-Short (All)': '4031',
        'Commercial Positions-Long (All)': '7301',
        'Commercial Positions-Short (All)': '12052',
        'Change in Noncommercial-Long (All)': '-292',
        'Change in Noncommercial-Short (All)': '-86',
        'Change in Commercial-Long (All)': '82',
        'Change in Commercial-Short (All)': '-2',
        '% of OI-Noncommercial-Long (All)': '14.3',
        '% of OI-Noncommercial-Short (All)': '17.2',
        '% of OI-Commercial-Long (All)': '31.1',
        '% of OI-Commercial-Short (All)': '51.3',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-02-04',
        'Open Interest (All)': '23841',
        'Noncommercial Positions-Long (All)': '3642',
        'Noncommercial Positions-Short (All)': '4117',
        'Commercial Positions-Long (All)': '7219',
        'Commercial Positions-Short (All)': '12054',
        'Change in Noncommercial-Long (All)': '-33',
        'Change in Noncommercial-Short (All)': '17',
        'Change in Commercial-Long (All)': '9',
        'Change in Commercial-Short (All)': '119',
        '% of OI-Noncommercial-Long (All)': '15.3',
        '% of OI-Noncommercial-Short (All)': '17.3',
        '% of OI-Commercial-Long (All)': '30.3',
        '% of OI-Commercial-Short (All)': '50.6',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-28',
        'Open Interest (All)': '23569',
        'Noncommercial Positions-Long (All)': '3675',
        'Noncommercial Positions-Short (All)': '4100',
        'Commercial Positions-Long (All)': '7210',
        'Commercial Positions-Short (All)': '11935',
        'Change in Noncommercial-Long (All)': '62',
        'Change in Noncommercial-Short (All)': '95',
        'Change in Commercial-Long (All)': '-139',
        'Change in Commercial-Short (All)': '91',
        '% of OI-Noncommercial-Long (All)': '15.6',
        '% of OI-Noncommercial-Short (All)': '17.4',
        '% of OI-Commercial-Long (All)': '30.6',
        '% of OI-Commercial-Short (All)': '50.6',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-21',
        'Open Interest (All)': '23148',
        'Noncommercial Positions-Long (All)': '3613',
        'Noncommercial Positions-Short (All)': '4005',
        'Commercial Positions-Long (All)': '7349',
        'Commercial Positions-Short (All)': '11844',
        'Change in Noncommercial-Long (All)': '76',
        'Change in Noncommercial-Short (All)': '1322',
        'Change in Commercial-Long (All)': '284',
        'Change in Commercial-Short (All)': '-511',
        '% of OI-Noncommercial-Long (All)': '15.6',
        '% of OI-Noncommercial-Short (All)': '17.3',
        '% of OI-Commercial-Long (All)': '31.7',
        '% of OI-Commercial-Short (All)': '51.2',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-14',
        'Open Interest (All)': '22585',
        'Noncommercial Positions-Long (All)': '3537',
        'Noncommercial Positions-Short (All)': '2683',
        'Commercial Positions-Long (All)': '7065',
        'Commercial Positions-Short (All)': '12355',
        'Change in Noncommercial-Long (All)': '42',
        'Change in Noncommercial-Short (All)': '160',
        'Change in Commercial-Long (All)': '7',
        'Change in Commercial-Short (All)': '96',
        '% of OI-Noncommercial-Long (All)': '15.7',
        '% of OI-Noncommercial-Short (All)': '11.9',
        '% of OI-Commercial-Long (All)': '31.3',
        '% of OI-Commercial-Short (All)': '54.7',
      },
      {
        market: 'EURO FX/BRITISH POUND XRATE',
        exchange: 'CHICAGO MERCANTILE EXCHANGE',
        'Market and Exchange Names':
          'EURO FX/BRITISH POUND XRATE - CHICAGO MERCANTILE EXCHANGE',
        'As of Date in Form YYYY-MM-DD': '2020-01-07',
        'Open Interest (All)': '22493',
        'Noncommercial Positions-Long (All)': '3495',
        'Noncommercial Positions-Short (All)': '2523',
        'Commercial Positions-Long (All)': '7058',
        'Commercial Positions-Short (All)': '12259',
        'Change in Noncommercial-Long (All)': '7',
        'Change in Noncommercial-Short (All)': '-1022',
        'Change in Commercial-Long (All)': '-1172',
        'Change in Commercial-Short (All)': '1',
        '% of OI-Noncommercial-Long (All)': '15.5',
        '% of OI-Noncommercial-Short (All)': '11.2',
        '% of OI-Commercial-Long (All)': '31.4',
        '% of OI-Commercial-Short (All)': '54.5',
      },
    ],
  },
}
